INFO     log:logger_util.py:42 ------接口测试开始啦------
INFO     log:logger_util.py:42 用例名称：新增用户
INFO     log:logger_util.py:42 请求路径：http://1.94.32.200:9090/v1/user
INFO     log:logger_util.py:42 请求方法：post
INFO     log:logger_util.py:42 请求耗时：60 ms
INFO     log:logger_util.py:42 预期结果：{'code': 200}
INFO     log:logger_util.py:42 实际结果：{'code': 201, 'msg': '用户名已存在', 'data': None}
INFO     log:logger_util.py:42 预期结果：{'msg': 'success'}
INFO     log:logger_util.py:42 实际结果：{'code': 201, 'msg': '用户名已存在', 'data': None}
INFO     log:logger_util.py:42 接口测试失败
INFO     log:logger_util.py:42 断言异常：
INFO     log:logger_util.py:42 ------接口测试结束------